export const ADD_TO_CART = "ADD_TO_CART";
export const CART_DATA_LIST = "CART_DATA_LIST";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const PRODUCT_LIST = "PRODUCT_LIST";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SEARCH_PRODUCT_LIST = "SEARCH_PRODUCT_LIST";
export const SET_SEARCH_PRODUCT_LIST = "SET_SEARCH_PRODUCT_LIST";

export const INCREASE_ITEM_QUNTITY = "INCREASE_QUNTITY";
export const DECREASE_ITEM_QUNTITY = "DECREASE_QUNTITY";
export const REMOVE_ITEM = "REMOVE_ITEM";
